#!/bin/bash

echo "==========================================="
echo "🔄 Reloading AI with Booking Flow Knowledge"
echo "==========================================="
echo ""

cd "/Users/tanujapaunikar/Desktop/Health Care"

# Clear caches
echo "Clearing cache..."
php artisan config:clear
php artisan cache:clear

# Seed booking flow knowledge
echo ""
echo "Adding booking flow knowledge to AI..."
php artisan db:seed --class=BookingFlowKnowledgeSeeder

# Seed additional knowledge (if not already done)
echo ""
echo "Ensuring all knowledge base resources are loaded..."
php artisan db:seed --class=AdditionalKnowledgeSeeder

echo ""
echo "==========================================="
echo "✅ Done! AI now understands booking flow"
echo "==========================================="
echo ""
echo "🎯 What Changed:"
echo ""
echo "1. AI now knows WHEN to show UI components"
echo "   - Shows doctor list when user wants to browse"
echo "   - Shows calendar when user wants to see availability"
echo "   - Shows payment UI for secure transactions"
echo ""
echo "2. AI now knows WHEN to use natural chat"
echo "   - Answers questions naturally (no UI components)"
echo "   - Handles simple confirmations via chat"
echo "   - Extracts info from natural language"
echo ""
echo "3. AI learned complete booking workflows"
echo "   - Doctor appointment flow (8 steps)"
echo "   - Lab test booking flow (6 steps)"
echo "   - When each step needs UI vs chat"
echo ""
echo "==========================================="
echo "🧪 Test These Scenarios:"
echo "==========================================="
echo ""
echo "1. QUESTION (should use natural chat, NO UI):"
echo "   - 'which doctor has better experience with gynaecology?'"
echo "   - 'what is the difference between video and in-person?'"
echo "   - 'how much does an appointment cost?'"
echo "   → Expected: Natural answer from knowledge base"
echo ""
echo "2. BROWSING REQUEST (should show UI):"
echo "   - 'show me all available doctors'"
echo "   - 'what time slots are available?'"
echo "   - 'let me see the packages'"
echo "   → Expected: Relevant UI component displayed"
echo ""
echo "3. COMPLETE INFO (should use natural chat):"
echo "   - 'book appointment with Dr. Rajesh tomorrow at 10am for myself'"
echo "   → Expected: Confirms naturally, skips unnecessary steps"
echo ""
echo "4. STEP-BY-STEP (should be conversational):"
echo "   - 'I want to see a doctor'"
echo "   - 'for my son'"
echo "   - 'new appointment'"
echo "   - 'Dr. Rajesh'"
echo "   → Expected: Natural flow with extracted entities"
echo ""
echo "==========================================="
echo ""
echo "💡 The AI should now:"
echo "   ✓ Answer questions naturally (never show UI for questions)"
echo "   ✓ Show UI only when user wants to browse or for complex selections"
echo "   ✓ Extract information from natural language"
echo "   ✓ Skip unnecessary steps when info is provided"
echo "   ✓ Maintain natural conversation flow"
echo ""
echo "🌐 Test at: http://localhost:3000/booking/"
echo ""
echo "📋 Check logs: tail -f storage/logs/laravel.log"
echo ""
