// Indian States and Union Territories
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const;

// Major cities by state
export const CITIES_BY_STATE: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Kadapa',
    'Anantapur',
    'Eluru',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
    'Adoni',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Pasighat',
    'Tawang',
    'Ziro',
    'Bomdila',
    'Tezu',
    'Seppa',
    'Along',
    'Roing',
  ],
  'Assam': [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Dhubri',
    'Diphu',
    'North Lakhimpur',
    'Goalpara',
    'Barpeta',
    'Karimganj',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Darbhanga',
    'Purnia',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chapra',
    'Saharsa',
    'Hajipur',
    'Sasaram',
    'Dehri',
    'Bettiah',
    'Motihari',
    'Bagaha',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Korba',
    'Durg',
    'Rajnandgaon',
    'Raigarh',
    'Jagdalpur',
    'Ambikapur',
    'Dhamtari',
    'Mahasamund',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Curchorem',
    'Sanquelim',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Gandhinagar',
    'Anand',
    'Nadiad',
    'Morbi',
    'Surendranagar',
    'Bharuch',
    'Vapi',
    'Navsari',
    'Veraval',
    'Porbandar',
    'Godhra',
    'Bhuj',
    'Palanpur',
  ],
  'Haryana': [
    'Faridabad',
    'Gurgaon',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Bhiwani',
    'Sirsa',
    'Bahadurgarh',
    'Jind',
    'Thanesar',
    'Kaithal',
    'Rewari',
    'Palwal',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Dharamshala',
    'Solan',
    'Mandi',
    'Palampur',
    'Baddi',
    'Nahan',
    'Una',
    'Kullu',
    'Hamirpur',
    'Bilaspur',
    'Chamba',
    'Kangra',
  ],
  'Jharkhand': [
    'Ranchi',
    'Jamshedpur',
    'Dhanbad',
    'Bokaro',
    'Deoghar',
    'Phusro',
    'Hazaribagh',
    'Giridih',
    'Ramgarh',
    'Medininagar',
    'Chirkunda',
  ],
  'Karnataka': [
    'Bengaluru',
    'Mysuru',
    'Mangaluru',
    'Hubballi',
    'Belagavi',
    'Kalaburagi',
    'Davangere',
    'Ballari',
    'Vijayapura',
    'Shivamogga',
    'Tumakuru',
    'Raichur',
    'Bidar',
    'Hospet',
    'Hassan',
    'Gadag',
    'Udupi',
    'Chitradurga',
  ],
  'Kerala': [
    'Thiruvananthapuram',
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Kollam',
    'Palakkad',
    'Alappuzha',
    'Malappuram',
    'Kannur',
    'Kottayam',
    'Kasaragod',
    'Pathanamthitta',
    'Idukki',
    'Wayanad',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Ratlam',
    'Satna',
    'Dewas',
    'Murwara',
    'Rewa',
    'Chhindwara',
    'Guna',
    'Shivpuri',
    'Vidisha',
    'Damoh',
    'Mandsaur',
    'Khargone',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Kolhapur',
    'Amravati',
    'Navi Mumbai',
    'Sangli',
    'Malegaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Jalgaon',
    'Ichalkaranji',
    'Parbhani',
    'Panvel',
    'Bhiwandi',
    'Nanded',
    'Satara',
    'Chandrapur',
    'Jalna',
  ],
  'Manipur': [
    'Imphal',
    'Thoubal',
    'Bishnupur',
    'Churachandpur',
    'Ukhrul',
    'Senapati',
  ],
  'Meghalaya': [
    'Shillong',
    'Tura',
    'Jowai',
    'Nongstoin',
    'Williamnagar',
  ],
  'Mizoram': [
    'Aizawl',
    'Lunglei',
    'Saiha',
    'Champhai',
    'Kolasib',
    'Serchhip',
  ],
  'Nagaland': [
    'Kohima',
    'Dimapur',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Balasore',
    'Bhadrak',
    'Baripada',
    'Jharsuguda',
    'Jeypore',
    'Bargarh',
    'Rayagada',
    'Balangir',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Mohali',
    'Pathankot',
    'Hoshiarpur',
    'Batala',
    'Moga',
    'Malerkotla',
    'Khanna',
    'Phagwara',
    'Muktsar',
    'Barnala',
    'Rajpura',
    'Firozpur',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Sri Ganganagar',
    'Kishangarh',
    'Tonk',
    'Beawar',
    'Hanumangarh',
  ],
  'Sikkim': [
    'Gangtok',
    'Namchi',
    'Geyzing',
    'Mangan',
    'Jorethang',
    'Rangpo',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Tiruppur',
    'Vellore',
    'Erode',
    'Thoothukkudi',
    'Dindigul',
    'Thanjavur',
    'Ranipet',
    'Sivakasi',
    'Karur',
    'Udhagamandalam',
    'Hosur',
    'Nagercoil',
    'Kancheepuram',
    'Kumarapalayam',
  ],
  'Telangana': [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Khammam',
    'Karimnagar',
    'Ramagundam',
    'Mahbubnagar',
    'Nalgonda',
    'Adilabad',
    'Suryapet',
    'Siddipet',
    'Miryalaguda',
    'Jagtial',
    'Mancherial',
  ],
  'Tripura': [
    'Agartala',
    'Dharmanagar',
    'Udaipur',
    'Kailasahar',
    'Belonia',
    'Khowai',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Ghaziabad',
    'Agra',
    'Varanasi',
    'Meerut',
    'Prayagraj',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Maunath Bhanjan',
    'Hapur',
    'Ayodhya',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Fatehpur',
    'Raebareli',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Pithoragarh',
    'Jaspur',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Dankuni',
    'Dhulian',
    'Raniganj',
    'Haldia',
    'Raiganj',
    'Krishnanagar',
    'Nabadwip',
    'Medinipur',
    'Jalpaiguri',
    'Balurghat',
    'Basirhat',
    'Bankura',
    'Chakdaha',
    'Darjeeling',
    'Alipurduar',
  ],
  'Andaman and Nicobar Islands': [
    'Port Blair',
    'Diglipur',
    'Rangat',
    'Car Nicobar',
  ],
  'Chandigarh': [
    'Chandigarh',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Daman',
    'Diu',
    'Silvassa',
  ],
  'Delhi': [
    'New Delhi',
    'Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'Central Delhi',
    'North East Delhi',
    'North West Delhi',
    'South East Delhi',
    'South West Delhi',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Sopore',
    'Kathua',
    'Udhampur',
  ],
  'Ladakh': [
    'Leh',
    'Kargil',
  ],
  'Lakshadweep': [
    'Kavaratti',
    'Agatti',
    'Minicoy',
  ],
  'Puducherry': [
    'Puducherry',
    'Karaikal',
    'Yanam',
    'Mahe',
  ],
};

// Get cities for a specific state
export function getCitiesForState(state: string): string[] {
  return CITIES_BY_STATE[state] || [];
}

// Get all cities (flattened)
export function getAllCities(): string[] {
  return Object.values(CITIES_BY_STATE).flat().sort();
}
